// ============================================================
// Andhra University — Mock Data  (Engineering Campus)
// ============================================================
window.AppData = {

  university: {
    name: "Andhra University",
    established: 1926,
    location: "Visakhapatnam, Andhra Pradesh, India",
    totalStudents: 12450,
    totalFaculty: 417,
    departments: 12,
    currentSemester: "Spring 2026",
    courses: 280
  },

  departments: [
    { id:1,  code:"ARCH",   name:"Architecture",                         head:"Prof. Ramesh Babu",        students: 580, faculty:22, building:"Architecture Block",          color:"#7c3aed", bg:"#f5f3ff", icon:"🏗️" },
    { id:2,  code:"CIVIL",  name:"Civil Engineering",                    head:"Dr. Srinivasa Rao",        students:1450, faculty:52, building:"Civil Engineering Block",     color:"#92400e", bg:"#fdf3e3", icon:"🏛️" },
    { id:3,  code:"CSE",    name:"Computer Science & Engineering",        head:"Dr. Venkat Reddy",         students:2200, faculty:58, building:"Computer Science Block",      color:"#1d4ed8", bg:"#eff6ff", icon:"💻" },
    { id:4,  code:"CHEM",   name:"Chemical Engineering",                 head:"Dr. Subrahmanyam",         students: 720, faculty:28, building:"Chemical Engineering Block",  color:"#ea580c", bg:"#fff7ed", icon:"⚗️" },
    { id:5,  code:"EEE",    name:"Electrical Engineering",               head:"Prof. Narayana Rao",       students:1380, faculty:48, building:"Electrical Engineering Block", color:"#b45309", bg:"#fffbeb", icon:"⚡" },
    { id:6,  code:"ENV",    name:"Environmental Engg. & Management",     head:"Dr. Padmavathi",           students: 480, faculty:18, building:"Environmental Block",         color:"#166534", bg:"#f0fdf4", icon:"🌿" },
    { id:7,  code:"GEO",    name:"Geo Engineering",                      head:"Dr. Krishnamurthy",        students: 420, faculty:16, building:"Geo Engineering Block",       color:"#4d7c0f", bg:"#f7fee7", icon:"🌍" },
    { id:8,  code:"ITCA",   name:"IT and Computer Applications",         head:"Prof. Lakshmi Narasimha",  students:1650, faculty:45, building:"IT Center",                   color:"#0e7490", bg:"#ecfeff", icon:"🖥️" },
    { id:9,  code:"MARINE", name:"Marine Engineering",                   head:"Dr. Satish Kumar",         students: 560, faculty:22, building:"Marine Engineering Block",    color:"#1e3a8a", bg:"#eff6ff", icon:"⚓" },
    { id:10, code:"MECH",   name:"Mechanical Engineering",               head:"Dr. Ranga Rao",            students:1820, faculty:62, building:"Mechanical Engineering Block", color:"#b91c1c", bg:"#fef2f2", icon:"⚙️" },
    { id:11, code:"META",   name:"Metallurgical Engineering",             head:"Dr. Subba Rao",            students: 480, faculty:18, building:"Metallurgy Block",            color:"#334155", bg:"#f8fafc", icon:"🔩" },
    { id:12, code:"INST",   name:"Instrument Technology",                head:"Prof. Satyanarayana",      students: 710, faculty:28, building:"Instrumentation Lab",         color:"#9d174d", bg:"#fdf2f8", icon:"🔬" },
  ],

  students: [
    { id:"S001", name:"Arjun Reddy",       age:20, year:2, dept:"CSE",    gpa:3.8, status:"Active",    email:"arjun.r@andhrauniv.ac.in",    phone:"+91-9441001001", advisor:"Dr. Venkat Reddy",        courses:["CSE201","CSE301","MATH201"], joined:"2024-09-01" },
    { id:"S002", name:"Bhavana Sharma",    age:22, year:4, dept:"MECH",   gpa:3.5, status:"Active",    email:"bhavana.s@andhrauniv.ac.in",  phone:"+91-9441001002", advisor:"Dr. Ranga Rao",           courses:["MECH401","MECH402"],         joined:"2022-09-01" },
    { id:"S003", name:"Chandra Sekhar",    age:19, year:1, dept:"CIVIL",  gpa:3.9, status:"Active",    email:"chandra.s@andhrauniv.ac.in",  phone:"+91-9441001003", advisor:"Dr. Srinivasa Rao",       courses:["CIVIL101","CIVIL102"],       joined:"2025-09-01" },
    { id:"S004", name:"Divya Lakshmi",     age:21, year:3, dept:"EEE",    gpa:3.7, status:"Active",    email:"divya.l@andhrauniv.ac.in",    phone:"+91-9441001004", advisor:"Prof. Narayana Rao",      courses:["EEE301","EEE302","EEE303"], joined:"2023-09-01" },
    { id:"S005", name:"Eswar Prasad",      age:20, year:2, dept:"CSE",    gpa:3.6, status:"Active",    email:"eswar.p@andhrauniv.ac.in",    phone:"+91-9441001005", advisor:"Dr. Venkat Reddy",        courses:["CSE201","CSE202"],           joined:"2024-09-01" },
    { id:"S006", name:"Fatima Begum",      age:23, year:4, dept:"ITCA",   gpa:3.4, status:"Active",    email:"fatima.b@andhrauniv.ac.in",   phone:"+91-9441001006", advisor:"Prof. Lakshmi Narasimha", courses:["ITCA401","ITCA402"],         joined:"2022-09-01" },
    { id:"S007", name:"Geetha Rani",       age:19, year:1, dept:"ARCH",   gpa:3.2, status:"Active",    email:"geetha.r@andhrauniv.ac.in",   phone:"+91-9441001007", advisor:"Prof. Ramesh Babu",       courses:["ARCH101","ARCH102"],         joined:"2025-09-01" },
    { id:"S008", name:"Harish Kumar",      age:21, year:3, dept:"MARINE", gpa:3.9, status:"Active",    email:"harish.k@andhrauniv.ac.in",   phone:"+91-9441001008", advisor:"Dr. Satish Kumar",        courses:["MARINE301","MARINE302"],     joined:"2023-09-01" },
    { id:"S009", name:"Indira Devi",       age:20, year:2, dept:"CHEM",   gpa:3.7, status:"Active",    email:"indira.d@andhrauniv.ac.in",   phone:"+91-9441001009", advisor:"Dr. Subrahmanyam",        courses:["CHEM201","CHEM202"],         joined:"2024-09-01" },
    { id:"S010", name:"Jagadish Babu",     age:22, year:3, dept:"MECH",   gpa:3.3, status:"Active",    email:"jagadish.b@andhrauniv.ac.in", phone:"+91-9441001010", advisor:"Dr. Ranga Rao",           courses:["MECH301","MECH302"],         joined:"2023-09-01" },
    { id:"S011", name:"Kavitha Nair",      age:21, year:3, dept:"CSE",    gpa:3.8, status:"Active",    email:"kavitha.n@andhrauniv.ac.in",  phone:"+91-9441001011", advisor:"Dr. Venkat Reddy",        courses:["CSE301","CSE302","CSE303"],  joined:"2023-09-01" },
    { id:"S012", name:"Lokesh Varma",      age:19, year:1, dept:"EEE",    gpa:3.1, status:"Active",    email:"lokesh.v@andhrauniv.ac.in",   phone:"+91-9441001012", advisor:"Prof. Narayana Rao",      courses:["EEE101","EEE103"],           joined:"2025-09-01" },
    { id:"S013", name:"Madhuri Srinivas",  age:20, year:2, dept:"INST",   gpa:3.9, status:"Active",    email:"madhuri.s@andhrauniv.ac.in",  phone:"+91-9441001013", advisor:"Prof. Satyanarayana",     courses:["INST201","INST202"],         joined:"2024-09-01" },
    { id:"S014", name:"Naresh Chandra",    age:22, year:4, dept:"CSE",    gpa:3.6, status:"Active",    email:"naresh.c@andhrauniv.ac.in",   phone:"+91-9441001014", advisor:"Dr. Venkat Reddy",        courses:["CSE401","CSE402","CSE403"],  joined:"2022-09-01" },
    { id:"S015", name:"Obalamma Rao",      age:21, year:3, dept:"CIVIL",  gpa:3.3, status:"Active",    email:"obalamma.r@andhrauniv.ac.in", phone:"+91-9441001015", advisor:"Dr. Srinivasa Rao",       courses:["CIVIL301","CIVIL302"],       joined:"2023-09-01" },
    { id:"S016", name:"Praveen Kumar",     age:20, year:2, dept:"META",   gpa:3.7, status:"Active",    email:"praveen.k@andhrauniv.ac.in",  phone:"+91-9441001016", advisor:"Dr. Subba Rao",           courses:["META201","META202"],         joined:"2024-09-01" },
    { id:"S017", name:"Radhika Menon",     age:19, year:1, dept:"ENV",    gpa:3.4, status:"Active",    email:"radhika.m@andhrauniv.ac.in",  phone:"+91-9441001017", advisor:"Dr. Padmavathi",          courses:["ENV101","ENV102"],           joined:"2025-09-01" },
    { id:"S018", name:"Santosh Patnaik",   age:23, year:4, dept:"ITCA",   gpa:3.8, status:"Active",    email:"santosh.p@andhrauniv.ac.in",  phone:"+91-9441001018", advisor:"Prof. Lakshmi Narasimha", courses:["ITCA401","ITCA402"],         joined:"2022-09-01" },
    { id:"S019", name:"Tejaswi Pavan",     age:21, year:3, dept:"GEO",    gpa:3.5, status:"Active",    email:"tejaswi.p@andhrauniv.ac.in",  phone:"+91-9441001019", advisor:"Dr. Krishnamurthy",       courses:["GEO301","GEO302"],           joined:"2023-09-01" },
    { id:"S020", name:"Usha Rani",         age:20, year:2, dept:"MARINE", gpa:3.6, status:"Active",    email:"usha.r@andhrauniv.ac.in",     phone:"+91-9441001020", advisor:"Dr. Satish Kumar",        courses:["MARINE201","MARINE202"],     joined:"2024-09-01" },
    { id:"S021", name:"Vamshi Krishna",    age:22, year:4, dept:"MECH",   gpa:3.9, status:"Probation", email:"vamshi.k@andhrauniv.ac.in",   phone:"+91-9441001021", advisor:"Dr. Ranga Rao",           courses:["MECH401","MECH402"],         joined:"2022-09-01" },
    { id:"S022", name:"Wahida Sultana",    age:19, year:1, dept:"CHEM",   gpa:3.2, status:"Active",    email:"wahida.s@andhrauniv.ac.in",   phone:"+91-9441001022", advisor:"Dr. Subrahmanyam",        courses:["CHEM101","CHEM102"],         joined:"2025-09-01" },
    { id:"S023", name:"Yaswanth Rao",      age:21, year:3, dept:"EEE",    gpa:3.5, status:"Active",    email:"yaswanth.r@andhrauniv.ac.in", phone:"+91-9441001023", advisor:"Prof. Narayana Rao",      courses:["EEE301","EEE302","EEE303"], joined:"2023-09-01" },
    { id:"S024", name:"Zeenath Fathima",   age:20, year:2, dept:"ARCH",   gpa:3.4, status:"Active",    email:"zeenath.f@andhrauniv.ac.in",  phone:"+91-9441001024", advisor:"Prof. Ramesh Babu",       courses:["ARCH201","ARCH202"],         joined:"2024-09-01" },
    { id:"S025", name:"Amarnath Gupta",    age:22, year:4, dept:"INST",   gpa:3.8, status:"Active",    email:"amarnath.g@andhrauniv.ac.in", phone:"+91-9441001025", advisor:"Prof. Satyanarayana",     courses:["INST401","INST402"],         joined:"2022-09-01" },
  ],

  faculty: [
    { id:"F001", name:"Dr. Venkat Reddy",        dept:"CSE",    title:"Professor & Dept. Head", email:"v.reddy@andhrauniv.ac.in",      phone:"+91-9440201001", specialization:"Artificial Intelligence & ML",  office:"CSB-301", officeHours:"Mon/Wed 2-4 PM",   courses:["CSE301","CSE401","CSE403"], publications:34, yearsExp:20 },
    { id:"F002", name:"Dr. Ranga Rao",           dept:"MECH",   title:"Professor & Dept. Head", email:"r.rao@andhrauniv.ac.in",        phone:"+91-9440201002", specialization:"Thermal Engineering",           office:"MEB-201", officeHours:"Tue/Thu 10-12 AM", courses:["MECH301","MECH401"],        publications:22, yearsExp:17 },
    { id:"F003", name:"Dr. Srinivasa Rao",       dept:"CIVIL",  title:"Professor & Dept. Head", email:"s.rao@andhrauniv.ac.in",        phone:"+91-9440201003", specialization:"Structural Engineering",        office:"CEB-102", officeHours:"Mon/Fri 9-11 AM",  courses:["CIVIL301","CIVIL401"],      publications:19, yearsExp:22 },
    { id:"F004", name:"Prof. Narayana Rao",      dept:"EEE",    title:"Professor & Dept. Head", email:"n.rao@andhrauniv.ac.in",        phone:"+91-9440201004", specialization:"Power Systems",                 office:"EEB-205", officeHours:"Wed/Thu 1-3 PM",   courses:["EEE301","EEE401"],          publications:27, yearsExp:18 },
    { id:"F005", name:"Prof. Ramesh Babu",       dept:"ARCH",   title:"Professor & Dept. Head", email:"r.babu@andhrauniv.ac.in",       phone:"+91-9440201005", specialization:"Urban Design & Planning",       office:"ARB-101", officeHours:"Tue/Thu 2-4 PM",   courses:["ARCH301","ARCH401"],        publications:14, yearsExp:15 },
    { id:"F006", name:"Dr. Subrahmanyam",        dept:"CHEM",   title:"Professor & Dept. Head", email:"subrahm@andhrauniv.ac.in",      phone:"+91-9440201006", specialization:"Process Engineering",           office:"CHB-108", officeHours:"Mon/Wed 11-1 PM",  courses:["CHEM301","CHEM401"],        publications:21, yearsExp:16 },
    { id:"F007", name:"Dr. Satish Kumar",        dept:"MARINE", title:"Professor & Dept. Head", email:"satish.k@andhrauniv.ac.in",    phone:"+91-9440201007", specialization:"Naval Architecture",            office:"MAB-210", officeHours:"Tue/Fri 3-5 PM",   courses:["MARINE301","MARINE401"],    publications:18, yearsExp:14 },
    { id:"F008", name:"Prof. Lakshmi Narasimha", dept:"ITCA",   title:"Professor & Dept. Head", email:"l.narasimha@andhrauniv.ac.in", phone:"+91-9440201008", specialization:"Cloud Computing & Big Data",    office:"ITC-402", officeHours:"Wed/Thu 10-12 AM", courses:["ITCA301","ITCA401"],        publications:16, yearsExp:12 },
    { id:"F009", name:"Dr. Krishnamurthy",       dept:"GEO",    title:"Professor & Dept. Head", email:"krishna.m@andhrauniv.ac.in",   phone:"+91-9440201009", specialization:"Geotechnical Engineering",      office:"GEB-115", officeHours:"Mon/Thu 1-3 PM",   courses:["GEO201","GEO301"],          publications:13, yearsExp:19 },
    { id:"F010", name:"Dr. Padmavathi",          dept:"ENV",    title:"Professor & Dept. Head", email:"padma.v@andhrauniv.ac.in",     phone:"+91-9440201010", specialization:"Environmental Impact Assess.",  office:"ENB-205", officeHours:"Tue/Fri 9-11 AM",  courses:["ENV201","ENV301"],          publications:11, yearsExp:13 },
    { id:"F011", name:"Dr. Subba Rao",           dept:"META",   title:"Professor & Dept. Head", email:"subba.r@andhrauniv.ac.in",     phone:"+91-9440201011", specialization:"Material Science & Corrosion",  office:"MTB-101", officeHours:"Mon/Wed 3-5 PM",   courses:["META201","META301"],        publications:17, yearsExp:21 },
    { id:"F012", name:"Prof. Satyanarayana",     dept:"INST",   title:"Professor & Dept. Head", email:"satyana@andhrauniv.ac.in",     phone:"+91-9440201012", specialization:"Control Systems & Sensors",     office:"INB-310", officeHours:"Thu/Fri 2-4 PM",   courses:["INST201","INST301"],        publications:15, yearsExp:14 },
    { id:"F013", name:"Dr. Murali Krishna",      dept:"CSE",    title:"Associate Professor",    email:"murali.k@andhrauniv.ac.in",    phone:"+91-9440201013", specialization:"Cybersecurity & Networks",      office:"CSB-212", officeHours:"Mon/Fri 2-4 PM",   courses:["CSE202","CSE302"],          publications:9,  yearsExp:10 },
    { id:"F014", name:"Dr. Prasanna Kumar",      dept:"MECH",   title:"Associate Professor",    email:"prasanna.k@andhrauniv.ac.in",  phone:"+91-9440201014", specialization:"Robotics & Automation",         office:"MEB-108", officeHours:"Tue/Thu 11-1 PM",  courses:["MECH201","MECH202"],        publications:8,  yearsExp:9  },
    { id:"F015", name:"Prof. Anjali Devi",       dept:"CIVIL",  title:"Assistant Professor",    email:"anjali.d@andhrauniv.ac.in",    phone:"+91-9440201015", specialization:"Transportation Engineering",    office:"CEB-210", officeHours:"Wed/Fri 10-12 AM", courses:["CIVIL101","CIVIL201"],      publications:6,  yearsExp:6  },
  ],

  classes: [
    { id:"CL001", course:"CSE201 - Data Structures & Algorithms", dept:"CSE",    faculty:"Dr. Venkat Reddy",        room:"CSB-101",  day:"Monday",    startTime:"09:00", endTime:"10:30", type:"Lecture", enrolled:110 },
    { id:"CL002", course:"MECH101 - Engineering Mechanics",       dept:"MECH",   faculty:"Dr. Prasanna Kumar",      room:"MEB-201",  day:"Monday",    startTime:"10:00", endTime:"11:30", type:"Lecture", enrolled:145 },
    { id:"CL003", course:"CIVIL101 - Building Materials",         dept:"CIVIL",  faculty:"Prof. Anjali Devi",       room:"CEB-101",  day:"Monday",    startTime:"11:00", endTime:"12:30", type:"Lecture", enrolled:120 },
    { id:"CL004", course:"MATH201 - Engineering Mathematics II",  dept:"CSE",    faculty:"Dr. Murali Krishna",      room:"CSB-201",  day:"Monday",    startTime:"14:00", endTime:"15:30", type:"Lecture", enrolled:198 },
    { id:"CL005", course:"CSE301 - Operating Systems",            dept:"CSE",    faculty:"Dr. Venkat Reddy",        room:"CSB-102",  day:"Monday",    startTime:"15:00", endTime:"16:30", type:"Lecture", enrolled:105 },
    { id:"CL006", course:"EEE201 - Circuits and Networks",        dept:"EEE",    faculty:"Prof. Narayana Rao",      room:"EEB-101",  day:"Tuesday",   startTime:"09:00", endTime:"10:30", type:"Lecture", enrolled:98  },
    { id:"CL007", course:"MARINE201 - Naval Architecture I",      dept:"MARINE", faculty:"Dr. Satish Kumar",        room:"MAB-101",  day:"Tuesday",   startTime:"10:00", endTime:"12:00", type:"Lab",     enrolled:45  },
    { id:"CL008", course:"CHEM101 - Chemical Process Principles", dept:"CHEM",   faculty:"Dr. Subrahmanyam",        room:"CHB-101",  day:"Tuesday",   startTime:"13:00", endTime:"14:30", type:"Lecture", enrolled:72  },
    { id:"CL009", course:"ARCH101 - Architectural Design I",      dept:"ARCH",   faculty:"Prof. Ramesh Babu",       room:"ARB-101",  day:"Tuesday",   startTime:"14:00", endTime:"16:00", type:"Studio",  enrolled:48  },
    { id:"CL010", course:"ITCA201 - Database Management Systems", dept:"ITCA",   faculty:"Prof. Lakshmi Narasimha", room:"ITC-Lab1", day:"Tuesday",   startTime:"15:00", endTime:"17:00", type:"Lab",     enrolled:65  },
    { id:"CL011", course:"CIVIL201 - Structural Analysis I",      dept:"CIVIL",  faculty:"Dr. Srinivasa Rao",       room:"CEB-201",  day:"Wednesday", startTime:"09:00", endTime:"10:30", type:"Lecture", enrolled:115 },
    { id:"CL012", course:"EEE301 - Power Systems I",              dept:"EEE",    faculty:"Prof. Narayana Rao",      room:"EEB-201",  day:"Wednesday", startTime:"11:00", endTime:"12:30", type:"Lecture", enrolled:88  },
    { id:"CL013", course:"META201 - Physical Metallurgy",         dept:"META",   faculty:"Dr. Subba Rao",           room:"MTB-201",  day:"Wednesday", startTime:"13:00", endTime:"14:30", type:"Lecture", enrolled:60  },
    { id:"CL014", course:"CSE401 - Machine Learning",             dept:"CSE",    faculty:"Dr. Venkat Reddy",        room:"CSB-103",  day:"Wednesday", startTime:"15:00", endTime:"16:30", type:"Lecture", enrolled:92  },
    { id:"CL015", course:"GEO201 - Soil Mechanics",               dept:"GEO",    faculty:"Dr. Krishnamurthy",       room:"GEB-101",  day:"Thursday",  startTime:"09:00", endTime:"10:30", type:"Lecture", enrolled:55  },
    { id:"CL016", course:"ENV201 - Environmental Impact Assess.", dept:"ENV",    faculty:"Dr. Padmavathi",          room:"ENB-101",  day:"Thursday",  startTime:"10:00", endTime:"12:00", type:"Lab",     enrolled:42  },
    { id:"CL017", course:"INST201 - Sensors and Transducers",     dept:"INST",   faculty:"Prof. Satyanarayana",     room:"INB-201",  day:"Thursday",  startTime:"13:00", endTime:"14:30", type:"Lecture", enrolled:68  },
    { id:"CL018", course:"MECH301 - Thermodynamics",              dept:"MECH",   faculty:"Dr. Ranga Rao",           room:"MEB-301",  day:"Thursday",  startTime:"14:00", endTime:"15:30", type:"Lecture", enrolled:130 },
    { id:"CL019", course:"ITCA301 - Web Technologies",            dept:"ITCA",   faculty:"Prof. Lakshmi Narasimha", room:"ITC-301",  day:"Thursday",  startTime:"16:00", endTime:"17:30", type:"Lecture", enrolled:118 },
    { id:"CL020", course:"CSE302 - Computer Networks",            dept:"CSE",    faculty:"Dr. Murali Krishna",      room:"CSB-204",  day:"Friday",    startTime:"09:00", endTime:"10:30", type:"Lecture", enrolled:88  },
    { id:"CL021", course:"ARCH201 - Building Construction",       dept:"ARCH",   faculty:"Prof. Ramesh Babu",       room:"ARB-201",  day:"Friday",    startTime:"10:00", endTime:"11:30", type:"Lecture", enrolled:52  },
    { id:"CL022", course:"MARINE301 - Marine Propulsion Systems", dept:"MARINE", faculty:"Dr. Satish Kumar",        room:"MAB-301",  day:"Friday",    startTime:"13:00", endTime:"14:30", type:"Lecture", enrolled:48  },
    { id:"CL023", course:"META101 - Introduction to Metallurgy",  dept:"META",   faculty:"Dr. Subba Rao",           room:"MTB-103",  day:"Friday",    startTime:"14:00", endTime:"15:30", type:"Lecture", enrolled:62  },
    { id:"CL024", course:"CSE403 - Cloud Computing",              dept:"CSE",    faculty:"Dr. Venkat Reddy",        room:"CSB-105",  day:"Friday",    startTime:"15:00", endTime:"16:30", type:"Lecture", enrolled:72  },
  ],

  events: [
    { id:"E001", title:"Spring Orientation 2026",       date:"2026-01-15", time:"09:00 AM", location:"Main Auditorium",          type:"Academic", organizer:"Dean's Office",       description:"Welcome ceremony for new students. Campus tour, faculty introductions and orientation.",    status:"Completed" },
    { id:"E002", title:"AU Tech Expo 2026",             date:"2026-03-20", time:"10:00 AM", location:"Engineering Block",        type:"Academic", organizer:"CSE and EEE Dept",    description:"Annual technology exhibition showcasing student innovations in AI, Robotics and IoT.",     status:"Completed" },
    { id:"E003", title:"Annual Sports Meet",            date:"2026-04-12", time:"08:00 AM", location:"University Stadium",       type:"Sports",   organizer:"Sports Committee",    description:"Inter-department sports with athletics, cricket, football and basketball.",                 status:"Upcoming"  },
    { id:"E004", title:"Campus Placement Drive 2026",   date:"2026-04-18", time:"10:00 AM", location:"Student Center",           type:"Career",   organizer:"Placement Cell",      description:"60+ core engineering companies recruiting. Dress code: Formal. Carry updated resume.",      status:"Upcoming"  },
    { id:"E005", title:"Cultural Fest - AU Vibes",      date:"2026-04-25", time:"05:00 PM", location:"Open Air Theater",         type:"Cultural", organizer:"Student Council",     description:"Annual cultural festival with live performances, art exhibits and food stalls.",            status:"Upcoming"  },
    { id:"E006", title:"Research Symposium",            date:"2026-05-05", time:"09:00 AM", location:"Conference Hall A",        type:"Academic", organizer:"Research Cell",       description:"Faculty and PhD student research presentations. Open to all departments.",                 status:"Upcoming"  },
    { id:"E007", title:"Industry Connect - VIZAG Steel",date:"2026-05-10", time:"02:00 PM", location:"Mechanical Seminar Hall",  type:"Workshop", organizer:"MECH and META Dept",  description:"VIZAG Steel and SAIL leaders sharing insights on metallurgy and mechanical engineering.",  status:"Upcoming"  },
    { id:"E008", title:"Alumni Meet 2026",              date:"2026-05-20", time:"06:00 PM", location:"Grand Hall",               type:"Social",   organizer:"Alumni Association",  description:"Annual gathering of Andhra University alumni. Networking dinner and awards ceremony.",    status:"Upcoming"  },
    { id:"E009", title:"Code-AU Hackathon 2026",        date:"2026-05-28", time:"09:00 AM", location:"CS Department",            type:"Academic", organizer:"CSE Dept and TechClub",description:"48-hour coding hackathon. Prize pool Rs.2 Lakh. Teams of 2-4. Register by May 20.",       status:"Upcoming"  },
    { id:"E010", title:"End Semester Convocation",      date:"2026-06-15", time:"10:00 AM", location:"Main Auditorium",          type:"Academic", organizer:"Dean's Office",       description:"Semester-end ceremony. Gold medal, best research and faculty excellence awards.",         status:"Upcoming"  },
  ],

  exams: [
    { id:"X001", course:"CSE201 - Data Structures",           dept:"CSE",    type:"Mid-Term", date:"2026-04-15", time:"09:00 AM", duration:"2 hrs",   room:"Exam Hall A",      invigilator:"Dr. Murali Krishna",      students:110 },
    { id:"X002", course:"MECH101 - Engineering Mechanics",    dept:"MECH",   type:"Mid-Term", date:"2026-04-15", time:"02:00 PM", duration:"2 hrs",   room:"Exam Hall B",      invigilator:"Dr. Prasanna Kumar",      students:145 },
    { id:"X003", course:"CIVIL101 - Building Materials",      dept:"CIVIL",  type:"Mid-Term", date:"2026-04-16", time:"09:00 AM", duration:"2 hrs",   room:"Exam Hall A",      invigilator:"Prof. Anjali Devi",       students:120 },
    { id:"X004", course:"EEE201 - Circuits and Networks",     dept:"EEE",    type:"Mid-Term", date:"2026-04-16", time:"02:00 PM", duration:"2 hrs",   room:"Exam Hall C",      invigilator:"Prof. Narayana Rao",      students:98  },
    { id:"X005", course:"MARINE201 - Naval Architecture I",   dept:"MARINE", type:"Mid-Term", date:"2026-04-17", time:"09:00 AM", duration:"2.5 hrs", room:"Exam Hall B",      invigilator:"Dr. Satish Kumar",        students:45  },
    { id:"X006", course:"ITCA201 - Database Management",      dept:"ITCA",   type:"Mid-Term", date:"2026-04-17", time:"02:00 PM", duration:"2 hrs",   room:"ITC Lab",          invigilator:"Prof. Lakshmi Narasimha", students:65  },
    { id:"X007", course:"CHEM101 - Chemical Process Princ.",  dept:"CHEM",   type:"Mid-Term", date:"2026-04-18", time:"09:00 AM", duration:"2 hrs",   room:"Exam Hall C",      invigilator:"Dr. Subrahmanyam",        students:72  },
    { id:"X008", course:"ARCH101 - Architectural Design I",   dept:"ARCH",   type:"Mid-Term", date:"2026-04-18", time:"02:00 PM", duration:"3 hrs",   room:"Architecture Hall",invigilator:"Prof. Ramesh Babu",       students:48  },
    { id:"X009", course:"CSE401 - Machine Learning",          dept:"CSE",    type:"Final",    date:"2026-06-02", time:"09:00 AM", duration:"3 hrs",   room:"Exam Hall A",      invigilator:"Dr. Venkat Reddy",        students:92  },
    { id:"X010", course:"MECH301 - Thermodynamics",           dept:"MECH",   type:"Final",    date:"2026-06-02", time:"02:00 PM", duration:"3 hrs",   room:"Exam Hall B",      invigilator:"Dr. Ranga Rao",           students:130 },
    { id:"X011", course:"CIVIL301 - Structural Analysis II",  dept:"CIVIL",  type:"Final",    date:"2026-06-03", time:"09:00 AM", duration:"3 hrs",   room:"Exam Hall C",      invigilator:"Dr. Srinivasa Rao",       students:115 },
    { id:"X012", course:"EEE301 - Power Systems I",           dept:"EEE",    type:"Final",    date:"2026-06-03", time:"02:00 PM", duration:"3 hrs",   room:"Exam Hall A",      invigilator:"Prof. Narayana Rao",      students:88  },
    { id:"X013", course:"CSE302 - Computer Networks",         dept:"CSE",    type:"Final",    date:"2026-06-04", time:"09:00 AM", duration:"3 hrs",   room:"CSB Lab",          invigilator:"Dr. Murali Krishna",      students:88  },
    { id:"X014", course:"MARINE301 - Marine Propulsion",      dept:"MARINE", type:"Final",    date:"2026-06-05", time:"08:00 AM", duration:"3 hrs",   room:"Marine Hall",      invigilator:"Dr. Satish Kumar",        students:48  },
    { id:"X015", course:"META201 - Physical Metallurgy",      dept:"META",   type:"Final",    date:"2026-06-06", time:"09:00 AM", duration:"3 hrs",   room:"Meta Lab",         invigilator:"Dr. Subba Rao",           students:60  },
    { id:"X016", course:"INST201 - Sensors and Transducers",  dept:"INST",   type:"Final",    date:"2026-06-06", time:"02:00 PM", duration:"3 hrs",   room:"Inst. Lab",        invigilator:"Prof. Satyanarayana",     students:68  },
  ],

  analytics: {
    yearwiseStrength: [
      { year:"Year 1 (2025-26)", students:3240 },
      { year:"Year 2 (2024-25)", students:3120 },
      { year:"Year 3 (2023-24)", students:2990 },
      { year:"Year 4 (2022-23)", students:3100 },
    ],
    enrollmentTrend: [
      { year:"2022", students: 9200 },
      { year:"2023", students: 9900 },
      { year:"2024", students:10800 },
      { year:"2025", students:11600 },
      { year:"2026", students:12450 },
    ],
    gpaDistribution: [
      { range:"3.5 - 4.0", count:3100 },
      { range:"3.0 - 3.5", count:4600 },
      { range:"2.5 - 3.0", count:3000 },
      { range:"2.0 - 2.5", count:1300 },
      { range:"Below 2.0", count: 450 },
    ],
    highDemandCourses: [
      { course:"Machine Learning",      dept:"CSE",    y2022:380, y2023:540, y2024:780, y2025:1020, y2026:1320 },
      { course:"Cloud Computing",       dept:"ITCA",   y2022:290, y2023:400, y2024:540, y2025:700,  y2026:880  },
      { course:"Robotics & Automation", dept:"MECH",   y2022:180, y2023:260, y2024:370, y2025:480,  y2026:620  },
      { course:"Smart Grid Technology", dept:"EEE",    y2022:200, y2023:280, y2024:390, y2025:510,  y2026:660  },
      { course:"Marine Robotics",       dept:"MARINE", y2022:100, y2023:150, y2024:210, y2025:290,  y2026:390  },
      { course:"Env. Data Science",     dept:"ENV",    y2022:110, y2023:165, y2024:230, y2025:310,  y2026:420  },
    ],
    placementStats: [
      { year:"2022", placed:3200, avg_package:6.2, highest:32 },
      { year:"2023", placed:3800, avg_package:7.1, highest:38 },
      { year:"2024", placed:4500, avg_package:8.4, highest:45 },
      { year:"2025", placed:5100, avg_package:9.8, highest:52 },
      { year:"2026", placed:4200, avg_package:10.5, highest:58 },
    ]
  },

  // ── FEES ─────────────────────────────────────────────────────
  fees: [
    { dept:"CSE",    name:"Computer Science & Engineering",   tuition:85000, exam:2500, library:1500, sports:500, misc:1000, hostel:48000, due:"2026-06-15" },
    { dept:"ITCA",   name:"IT and Computer Applications",     tuition:82000, exam:2500, library:1500, sports:500, misc:1000, hostel:48000, due:"2026-06-15" },
    { dept:"EEE",    name:"Electrical Engineering",           tuition:80000, exam:2500, library:1500, sports:500, misc:1000, hostel:48000, due:"2026-06-15" },
    { dept:"MECH",   name:"Mechanical Engineering",           tuition:80000, exam:2500, library:1500, sports:500, misc:1000, hostel:48000, due:"2026-06-15" },
    { dept:"CIVIL",  name:"Civil Engineering",                tuition:78000, exam:2500, library:1500, sports:500, misc:1000, hostel:48000, due:"2026-06-15" },
    { dept:"CHEM",   name:"Chemical Engineering",             tuition:78000, exam:2500, library:1500, sports:500, misc:1000, hostel:48000, due:"2026-06-15" },
    { dept:"MARINE", name:"Marine Engineering",               tuition:88000, exam:2500, library:1500, sports:500, misc:1000, hostel:48000, due:"2026-06-15" },
    { dept:"ARCH",   name:"Architecture",                     tuition:82000, exam:2500, library:1500, sports:500, misc:1000, hostel:48000, due:"2026-06-15" },
    { dept:"ENV",    name:"Environmental Engg. & Management", tuition:75000, exam:2500, library:1500, sports:500, misc:1000, hostel:48000, due:"2026-06-15" },
    { dept:"GEO",    name:"Geo Engineering",                  tuition:75000, exam:2500, library:1500, sports:500, misc:1000, hostel:48000, due:"2026-06-15" },
    { dept:"META",   name:"Metallurgical Engineering",        tuition:76000, exam:2500, library:1500, sports:500, misc:1000, hostel:48000, due:"2026-06-15" },
    { dept:"INST",   name:"Instrument Technology",            tuition:78000, exam:2500, library:1500, sports:500, misc:1000, hostel:48000, due:"2026-06-15" },
  ],

  // ── PLACEMENTS ───────────────────────────────────────────────
  placements: [
    { company:"Google",          type:"Tech",    package:42, dept:"CSE",    year:2026, students:8,  logo:"G" },
    { company:"Microsoft",       type:"Tech",    package:38, dept:"CSE",    year:2026, students:12, logo:"M" },
    { company:"Amazon",          type:"Tech",    package:35, dept:"ITCA",   year:2026, students:15, logo:"A" },
    { company:"Infosys",         type:"IT",      package:6.5,dept:"CSE",   year:2026, students:85, logo:"I" },
    { company:"TCS",             type:"IT",      package:7.0,dept:"CSE",   year:2026, students:120,logo:"T" },
    { company:"Wipro",           type:"IT",      package:6.0,dept:"ITCA",  year:2026, students:70, logo:"W" },
    { company:"L&T Engineering", type:"Core",    package:9.5,dept:"MECH",  year:2026, students:30, logo:"L" },
    { company:"BHEL",            type:"Core",    package:8.2,dept:"EEE",   year:2026, students:25, logo:"B" },
    { company:"ONGC",            type:"Core",    package:10.0,dept:"CHEM", year:2026, students:18, logo:"O" },
    { company:"Accenture",       type:"IT",      package:7.5,dept:"CSE",   year:2026, students:60, logo:"A" },
    { company:"Cognizant",       type:"IT",      package:6.8,dept:"ITCA",  year:2026, students:55, logo:"C" },
    { company:"HCL",             type:"IT",      package:6.2,dept:"CSE",   year:2026, students:45, logo:"H" },
    { company:"Mazagon Dock",    type:"Core",    package:11.5,dept:"MARINE",year:2026,students:20, logo:"M" },
    { company:"NTPC",            type:"Core",    package:9.0,dept:"EEE",   year:2026, students:22, logo:"N" },
    { company:"Samsung R&D",     type:"Tech",    package:28, dept:"INST",  year:2026, students:6,  logo:"S" },
  ],

  internships: [
    { company:"DRDO",         role:"Research Intern",         dept:"MECH",  duration:"6 months", stipend:15000, status:"Open",   deadline:"2026-05-01" },
    { company:"ISRO",         role:"Aerospace Systems Intern",dept:"MECH",  duration:"3 months", stipend:12000, status:"Open",   deadline:"2026-04-25" },
    { company:"Google",       role:"SWE Intern",              dept:"CSE",   duration:"3 months", stipend:80000, status:"Open",   deadline:"2026-04-30" },
    { company:"Microsoft",    role:"Cloud Intern",            dept:"ITCA",  duration:"6 months", stipend:60000, status:"Closed", deadline:"2026-03-15" },
    { company:"L&T",          role:"Site Engineering Intern", dept:"CIVIL", duration:"2 months", stipend:8000,  status:"Open",   deadline:"2026-05-10" },
    { company:"ONGC",         role:"Process Intern",          dept:"CHEM",  duration:"2 months", stipend:10000, status:"Open",   deadline:"2026-05-15" },
    { company:"Port Trust",   role:"Marine Ops Intern",       dept:"MARINE",duration:"3 months", stipend:9000,  status:"Open",   deadline:"2026-04-28" },
    { company:"AWS",          role:"DevOps Intern",           dept:"CSE",   duration:"6 months", stipend:70000, status:"Open",   deadline:"2026-05-05" },
  ],

  hackathons: [
    { name:"Smart India Hackathon 2026",     date:"2026-07-15", prize:"₹1,00,000", participants:420, dept:"All",   status:"Upcoming", org:"Govt of India" },
    { name:"AU TechFest CodeSprint",         date:"2026-05-20", prize:"₹50,000",   participants:280, dept:"CSE",   status:"Upcoming", org:"AU CSE Dept" },
    { name:"IEEE Xtreme 2026",               date:"2026-10-25", prize:"Trophy",     participants:90,  dept:"CSE",   status:"Upcoming", org:"IEEE" },
    { name:"Robo Wars AU",                   date:"2026-08-10", prize:"₹30,000",   participants:150, dept:"MECH",  status:"Upcoming", org:"AU MECH Dept" },
    { name:"Green Tech Challenge",           date:"2026-06-05", prize:"₹25,000",   participants:80,  dept:"ENV",   status:"Upcoming", org:"AU ENV Dept" },
    { name:"HackAndhra 2025",               date:"2025-11-10", prize:"₹75,000",   participants:350, dept:"All",   status:"Completed",org:"TechMahindra" },
    { name:"Marine Innovation Challenge",   date:"2026-09-18", prize:"₹40,000",   participants:60,  dept:"MARINE",status:"Upcoming", org:"Mazagon Dock" },
  ],

  // ── CERTIFICATES ─────────────────────────────────────────────
  certificates: [
    { id:"CERT001", student:"Arjun Reddy",     sid:"AU2023001", type:"Bonafide",         issued:"2026-01-10", status:"Issued",   validity:"6 months" },
    { id:"CERT002", student:"Bhavana Sharma",  sid:"AU2023002", type:"Transcript",        issued:"2026-02-15", status:"Issued",   validity:"Lifetime" },
    { id:"CERT003", student:"Charan Kumar",    sid:"AU2023003", type:"Degree Certificate",issued:"2026-03-20", status:"Issued",   validity:"Lifetime" },
    { id:"CERT004", student:"Divya Nair",      sid:"AU2023004", type:"Migration",         issued:null,         status:"Pending",  validity:"—" },
    { id:"CERT005", student:"Eshan Patel",     sid:"AU2023005", type:"Character",         issued:"2026-03-01", status:"Issued",   validity:"3 months" },
    { id:"CERT006", student:"Fatima Begum",    sid:"AU2023006", type:"Bonafide",          issued:null,         status:"Processing",validity:"—" },
    { id:"CERT007", student:"Gopal Varma",     sid:"AU2023007", type:"Degree Certificate",issued:"2026-04-01", status:"Issued",   validity:"Lifetime" },
    { id:"CERT008", student:"Haritha Reddy",   sid:"AU2023008", type:"Transcript",        issued:null,         status:"Pending",  validity:"—" },
    { id:"CERT009", student:"Ishaan Mehta",    sid:"AU2023009", type:"Provisional",       issued:"2026-03-10", status:"Issued",   validity:"1 year" },
    { id:"CERT010", student:"Jayalakshmi",     sid:"AU2023010", type:"Character",         issued:null,         status:"Processing",validity:"—" },
  ],

  // ── LIBRARY ──────────────────────────────────────────────────
  library: {
    totalBooks: 85420,
    available:  62300,
    borrowed:   23120,
    members:    11800,
    sections: [
      { name:"Engineering & Technology", books:32000, available:24000 },
      { name:"Science & Mathematics",    books:18000, available:13500 },
      { name:"Management & Commerce",    books:8000,  available:5800  },
      { name:"Arts & Humanities",        books:12000, available:9200  },
      { name:"Journals & Periodicals",   books:9420,  available:7200  },
      { name:"Digital Resources",        books:6000,  available:6000  },
    ],
    books: [
      { id:"LIB001", title:"Introduction to Algorithms",           author:"Cormen et al.",       dept:"CSE",   copies:8,  available:3, due:"2026-04-20" },
      { id:"LIB002", title:"Structural Analysis",                   author:"R.C. Hibbeler",       dept:"CIVIL", copies:6,  available:2, due:"2026-04-18" },
      { id:"LIB003", title:"Electric Machinery Fundamentals",       author:"Stephen Chapman",     dept:"EEE",   copies:5,  available:5, due:null },
      { id:"LIB004", title:"Fluid Mechanics",                       author:"Frank White",         dept:"MECH",  copies:7,  available:4, due:"2026-04-22" },
      { id:"LIB005", title:"Digital Image Processing",             author:"Gonzalez & Woods",    dept:"ITCA",  copies:4,  available:1, due:"2026-04-25" },
      { id:"LIB006", title:"Marine Engineering Practice",          author:"McGeorge",            dept:"MARINE",copies:3,  available:3, due:null },
      { id:"LIB007", title:"Environmental Engineering",            author:"Howard Peavy",        dept:"ENV",   copies:5,  available:2, due:"2026-04-19" },
      { id:"LIB008", title:"Theory of Machines",                   author:"S.S. Rattan",         dept:"MECH",  copies:10, available:6, due:"2026-04-21" },
      { id:"LIB009", title:"Computer Networks",                    author:"Andrew Tanenbaum",    dept:"CSE",   copies:6,  available:0, due:"2026-04-17" },
      { id:"LIB010", title:"Metallurgical Thermodynamics",         author:"D.R. Gaskell",        dept:"META",  copies:4,  available:4, due:null },
    ]
  },

  // ── HOSTEL ───────────────────────────────────────────────────
  hostel: {
    totalCapacity: 4800,
    occupied:      4210,
    blocks: [
      { block:"Block A (Boys)",   rooms:200, capacity:800, occupied:780, warden:"Mr. Suresh Kumar",   type:"Boys",  amenities:["WiFi","Mess","Gym","Laundry"] },
      { block:"Block B (Boys)",   rooms:200, capacity:800, occupied:762, warden:"Mr. Ravi Shankar",   type:"Boys",  amenities:["WiFi","Mess","Reading Room"] },
      { block:"Block C (Boys)",   rooms:150, capacity:600, occupied:555, warden:"Mr. Prasad Rao",     type:"Boys",  amenities:["WiFi","Mess","Sports Ground"] },
      { block:"Block D (Girls)",  rooms:200, capacity:800, occupied:798, warden:"Mrs. Lakshmi Devi",  type:"Girls", amenities:["WiFi","Mess","Gym","Salon"] },
      { block:"Block E (Girls)",  rooms:200, capacity:800, occupied:315, warden:"Mrs. Annapurna",     type:"Girls", amenities:["WiFi","Mess","Reading Room"] },
      { block:"PG Block",         rooms:100, capacity:400, occupied:380, warden:"Dr. Narasimha Rao",  type:"PG",    amenities:["WiFi","Mess","AC Rooms","Study Hall"] },
    ],
    messMenu: {
      breakfast: "Idli / Dosa / Upma + Tea/Coffee",
      lunch:     "Rice + Dal + Sabzi + Curd + Salad",
      snacks:    "Samosa / Biscuits + Tea",
      dinner:    "Chapati / Rice + Curry + Sweet (alternate days)"
    }
  },

  // ── ALUMNI ───────────────────────────────────────────────────
  alumni: [
    { id:"ALU001", name:"Dr. Ravi Teja Nalla",      batch:2005, dept:"CSE",   role:"CTO",             company:"Microsoft India",    location:"Hyderabad",  img:"R" },
    { id:"ALU002", name:"Smt. Anitha Krishnaswamy", batch:2008, dept:"CIVIL", role:"Chief Engineer",  company:"L&T Infrastructure", location:"Chennai",    img:"A" },
    { id:"ALU003", name:"Mr. Kiran Babu Yeluri",    batch:2010, dept:"MECH",  role:"Senior Scientist",company:"ISRO",               location:"Bangalore",  img:"K" },
    { id:"ALU004", name:"Ms. Pavani Reddy",         batch:2012, dept:"ITCA",  role:"Product Manager", company:"Google",             location:"New York",   img:"P" },
    { id:"ALU005", name:"Mr. Srikanth Varma",       batch:2007, dept:"EEE",   role:"Director",        company:"BHEL",               location:"New Delhi",  img:"S" },
    { id:"ALU006", name:"Dr. Madhavi Latha",        batch:2003, dept:"CHEM",  role:"Research Lead",   company:"ONGC R&D",           location:"Dehradun",   img:"M" },
    { id:"ALU007", name:"Mr. Prasanna Kumar",       batch:2015, dept:"CSE",   role:"SDE-III",         company:"Amazon",             location:"Seattle",    img:"P" },
    { id:"ALU008", name:"Ms. Vasudha Naidu",        batch:2014, dept:"MARINE",role:"Naval Architect",  company:"Mazagon Dock",       location:"Mumbai",     img:"V" },
    { id:"ALU009", name:"Mr. Satya Narayana",       batch:2009, dept:"META",  role:"VP Operations",   company:"Tata Steel",         location:"Jamshedpur", img:"S" },
    { id:"ALU010", name:"Dr. Supriya Rao",          batch:2006, dept:"ENV",   role:"Director",        company:"CPCB",               location:"New Delhi",  img:"S" },
    { id:"ALU011", name:"Mr. Vamsi Krishna",        batch:2018, dept:"CSE",   role:"Founder & CEO",   company:"TechVeda AI",        location:"Bangalore",  img:"V" },
    { id:"ALU012", name:"Ms. Lalitha Devi",         batch:2016, dept:"INST",  role:"Systems Engineer",company:"DRDO",               location:"Hyderabad",  img:"L" },
  ],

  // ── NOTIFICATIONS ────────────────────────────────────────────
  notifications: [
    { id:1, type:"exam",      title:"Mid-Term Exams Starting",          msg:"CSE mid-terms begin April 15. Hall tickets available at exam portal.", time:"2 hours ago",   read:false },
    { id:2, type:"fee",       title:"Fee Payment Reminder",             msg:"Last date for Spring 2026 fee payment is June 15, 2026. Pay before due date to avoid penalty.", time:"1 day ago",    read:false },
    { id:3, type:"placement", title:"Google Campus Drive",              msg:"Google is visiting campus on April 20 for SWE roles. Register by April 18.", time:"2 days ago",   read:false },
    { id:4, type:"event",     title:"TechFest 2026 Registrations Open", msg:"Register now for TechFest 2026. Last date: April 25.", time:"3 days ago",   read:true  },
    { id:5, type:"general",   title:"Library Notice",                   msg:"Library will remain closed on April 14 (Dr. Ambedkar Jayanti). Plan accordingly.", time:"4 days ago",   read:true  },
    { id:6, type:"exam",      title:"End Semester Schedule Released",   msg:"End semester timetable for all departments is now available in the Exam section.", time:"5 days ago",   read:true  },
    { id:7, type:"placement", title:"Infosys Walk-in Drive",            msg:"Infosys off-campus walk-in on April 22 for 2026 batch. Register at career portal.", time:"1 week ago",   read:true  },
    { id:8, type:"general",   title:"Sports Day 2026",                  msg:"Annual Sports Day on May 5. Registration for events opens April 20.", time:"1 week ago",   read:true  },
  ]
};
